# Generated by Django 4.1 on 2022-08-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='images/gallery')),
                ('image_min', models.FileField(upload_to='images/gallery')),
                ('alt', models.CharField(max_length=100)),
            ],
        ),
    ]
