# Generated by Django 4.1 on 2022-08-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evina', '0002_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Image',
        ),
    ]
