# Generated by Django 4.1 on 2022-09-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evina', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
