# Generated by Django 4.1 on 2022-09-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='header2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='header3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='header4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='header5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='header6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='header7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='header8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='header9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.FileField(blank=True, upload_to='images/gallery'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.FileField(blank=True, upload_to='images/gallery'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.FileField(blank=True, upload_to='images/gallery'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image4',
            field=models.FileField(blank=True, upload_to='images/gallery'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image5',
            field=models.FileField(blank=True, upload_to='images/gallery'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text10',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text6',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text7',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text8',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text9',
            field=models.TextField(blank=True),
        ),
    ]
