# Generated by Django 4.1 on 2022-09-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_header10_alter_post_header2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.FileField(blank=True, upload_to='static/images/gallery'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.FileField(blank=True, upload_to='static/images/gallery'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.FileField(blank=True, upload_to='static/images/gallery'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image4',
            field=models.FileField(blank=True, upload_to='static/images/gallery'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image5',
            field=models.FileField(blank=True, upload_to='static/images/gallery'),
        ),
    ]
